/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      // ── Nexora brand fonts ───────────────────────────────────────────────
      fontFamily: {
        playfair: ["'Playfair Display'", 'serif'],
        inter:    ["'Inter'",            'sans-serif'],
        mono:     ["'IBM Plex Mono'",    'monospace'],
        // Stitch system names (kept for legacy classes)
        'headline-xl': ["'Noto Serif'", 'serif'],
        'headline-lg': ["'Noto Serif'", 'serif'],
        'headline-md': ["'Noto Serif'", 'serif'],
        'body-lg':     ["'Inter'",      'sans-serif'],
        'body-md':     ["'Inter'",      'sans-serif'],
        'label-sm':    ["'Inter'",      'sans-serif'],
      },

      // ── Nexora design tokens (from Stitch DESIGN.md) ─────────────────────
      colors: {
        'on-secondary':              '#ffffff',
        'surface-variant':           '#e2e2e2',
        'error-container':           '#ffdad6',
        'secondary':                 '#5e5e5e',
        'surface-container-low':     '#f3f3f3',
        'on-surface-variant':        '#444748',
        'on-tertiary-fixed-variant': '#93000b',
        'on-primary':                '#ffffff',
        'tertiary-container':        '#410002',
        'primary':                   '#000000',
        'on-primary-container':      '#858383',
        'surface-container-lowest':  '#ffffff',
        'tertiary-fixed-dim':        '#ffb4ab',
        'on-primary-fixed-variant':  '#474646',
        'on-tertiary-container':     '#f63a35',
        'surface-dim':               '#dadada',
        'primary-fixed':             '#e5e2e1',
        'on-secondary-fixed':        '#1b1c1c',
        'secondary-fixed-dim':       '#c7c6c6',
        'outline-variant':           '#c4c7c7',
        'surface-tint':              '#5f5e5e',
        'primary-container':         '#1c1b1b',
        'outline':                   '#747878',
        'on-primary-fixed':          '#1c1b1b',
        'inverse-surface':           '#2f3131',
        'on-background':             '#1a1c1c',
        'surface-container-high':    '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'tertiary':                  '#000000',
        'on-tertiary':               '#ffffff',
        'on-tertiary-fixed':         '#410002',
        'surface':                   '#f9f9f9',
        'on-secondary-fixed-variant':'#464747',
        'inverse-primary':           '#c9c6c5',
        'surface-bright':            '#f9f9f9',
        'tertiary-fixed':            '#ffdad6',
        'error':                     '#ba1a1a',
        'inverse-on-surface':        '#f0f1f1',
        'primary-fixed-dim':         '#c9c6c5',
        'background':                '#f9f9f9',
        'on-error-container':        '#93000a',
        'surface-container':         '#eeeeee',
        'secondary-container':       '#e1dfdf',
        'on-error':                  '#ffffff',
        'on-secondary-container':    '#626262',
        'on-surface':                '#1a1c1c',
        'secondary-fixed':           '#e4e2e2',
      },

      borderRadius: {
        DEFAULT: '0px',
        lg:      '0px',
        xl:      '0px',
        full:    '9999px',
      },

      spacing: {
        unit:            '4px',
        'section-gap':   '128px',
        'container-max': '1440px',
        margin:          '64px',
        gutter:          '32px',
      },

      fontSize: {
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '400' }],
        'body-lg':     ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':     ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm':    ['12px', { lineHeight: '1',   letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
